// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gofiber/fiber/v3"
	"oauth2/app/routes"
)

// Injectors from wire.go:

func InitializeFiberServer() *fiber.App {
	app := routes.NewRouter()
	return app
}
