// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/repositories/sql_repo/auth_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "oauth2/app/global/model"
	models "oauth2/app/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIAuthRepository is a mock of IAuthRepository interface.
type MockIAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthRepositoryMockRecorder
}

// MockIAuthRepositoryMockRecorder is the mock recorder for MockIAuthRepository.
type MockIAuthRepositoryMockRecorder struct {
	mock *MockIAuthRepository
}

// NewMockIAuthRepository creates a new mock instance.
func NewMockIAuthRepository(ctrl *gomock.Controller) *MockIAuthRepository {
	mock := &MockIAuthRepository{ctrl: ctrl}
	mock.recorder = &MockIAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthRepository) EXPECT() *MockIAuthRepositoryMockRecorder {
	return m.recorder
}

// GetUserByUsernameOrEmail mocks base method.
func (m *MockIAuthRepository) GetUserByUsernameOrEmail(username, email string, ctx context.Context) (*models.Users, *model.ErrorLog) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsernameOrEmail", username, email, ctx)
	ret0, _ := ret[0].(*models.Users)
	ret1, _ := ret[1].(*model.ErrorLog)
	return ret0, ret1
}

// GetUserByUsernameOrEmail indicates an expected call of GetUserByUsernameOrEmail.
func (mr *MockIAuthRepositoryMockRecorder) GetUserByUsernameOrEmail(username, email, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsernameOrEmail", reflect.TypeOf((*MockIAuthRepository)(nil).GetUserByUsernameOrEmail), username, email, ctx)
}
