// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/repositories/mongo_repo/refresh_token_sessions_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "oauth2/app/global/model"
	models "oauth2/app/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIRefreshTokenSessionsRepository is a mock of IRefreshTokenSessionsRepository interface.
type MockIRefreshTokenSessionsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRefreshTokenSessionsRepositoryMockRecorder
}

// MockIRefreshTokenSessionsRepositoryMockRecorder is the mock recorder for MockIRefreshTokenSessionsRepository.
type MockIRefreshTokenSessionsRepositoryMockRecorder struct {
	mock *MockIRefreshTokenSessionsRepository
}

// NewMockIRefreshTokenSessionsRepository creates a new mock instance.
func NewMockIRefreshTokenSessionsRepository(ctrl *gomock.Controller) *MockIRefreshTokenSessionsRepository {
	mock := &MockIRefreshTokenSessionsRepository{ctrl: ctrl}
	mock.recorder = &MockIRefreshTokenSessionsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRefreshTokenSessionsRepository) EXPECT() *MockIRefreshTokenSessionsRepositoryMockRecorder {
	return m.recorder
}

// GetByRefreshToken mocks base method.
func (m *MockIRefreshTokenSessionsRepository) GetByRefreshToken(refreshToken string, ctx context.Context) (*models.RefreshTokenSession, *model.ErrorLog) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRefreshToken", refreshToken, ctx)
	ret0, _ := ret[0].(*models.RefreshTokenSession)
	ret1, _ := ret[1].(*model.ErrorLog)
	return ret0, ret1
}

// GetByRefreshToken indicates an expected call of GetByRefreshToken.
func (mr *MockIRefreshTokenSessionsRepositoryMockRecorder) GetByRefreshToken(refreshToken, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRefreshToken", reflect.TypeOf((*MockIRefreshTokenSessionsRepository)(nil).GetByRefreshToken), refreshToken, ctx)
}

// Insert mocks base method.
func (m *MockIRefreshTokenSessionsRepository) Insert(request *models.RefreshTokenSession, ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Insert", request, ctx)
}

// Insert indicates an expected call of Insert.
func (mr *MockIRefreshTokenSessionsRepositoryMockRecorder) Insert(request, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIRefreshTokenSessionsRepository)(nil).Insert), request, ctx)
}
