// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/repositories/mongo_repo/access_token_sessions_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "oauth2/app/global/model"
	models "oauth2/app/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIAccessTokenSessionsRepository is a mock of IAccessTokenSessionsRepository interface.
type MockIAccessTokenSessionsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAccessTokenSessionsRepositoryMockRecorder
}

// MockIAccessTokenSessionsRepositoryMockRecorder is the mock recorder for MockIAccessTokenSessionsRepository.
type MockIAccessTokenSessionsRepositoryMockRecorder struct {
	mock *MockIAccessTokenSessionsRepository
}

// NewMockIAccessTokenSessionsRepository creates a new mock instance.
func NewMockIAccessTokenSessionsRepository(ctrl *gomock.Controller) *MockIAccessTokenSessionsRepository {
	mock := &MockIAccessTokenSessionsRepository{ctrl: ctrl}
	mock.recorder = &MockIAccessTokenSessionsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAccessTokenSessionsRepository) EXPECT() *MockIAccessTokenSessionsRepositoryMockRecorder {
	return m.recorder
}

// GetByAccessToken mocks base method.
func (m *MockIAccessTokenSessionsRepository) GetByAccessToken(accessToken string, ctx context.Context) (*models.AccessTokenSession, *model.ErrorLog) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccessToken", accessToken, ctx)
	ret0, _ := ret[0].(*models.AccessTokenSession)
	ret1, _ := ret[1].(*model.ErrorLog)
	return ret0, ret1
}

// GetByAccessToken indicates an expected call of GetByAccessToken.
func (mr *MockIAccessTokenSessionsRepositoryMockRecorder) GetByAccessToken(accessToken, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccessToken", reflect.TypeOf((*MockIAccessTokenSessionsRepository)(nil).GetByAccessToken), accessToken, ctx)
}

// Insert mocks base method.
func (m *MockIAccessTokenSessionsRepository) Insert(request *models.AccessTokenSession, ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Insert", request, ctx)
}

// Insert indicates an expected call of Insert.
func (mr *MockIAccessTokenSessionsRepositoryMockRecorder) Insert(request, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIAccessTokenSessionsRepository)(nil).Insert), request, ctx)
}
